-- Owner-scoped metadata and deletion audit state for private artifacts.

create table public.artifacts (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id),
    kind varchar(32) not null,
    original_name varchar(255) not null,
    content_type varchar(255) not null,
    size_bytes bigint not null,
    sha256 varchar(64) not null,
    storage_bucket varchar(100) not null default 'arya-artifacts',
    storage_key text not null,
    status varchar(16) not null default 'active',
    last_error varchar(64) null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    deleted_at timestamptz null,
    constraint uq_artifact_storage_object
        unique (storage_bucket, storage_key),
    constraint ck_artifact_size check (size_bytes >= 0),
    constraint ck_artifact_sha256
        check (sha256 ~ '^[0-9a-f]{64}$'),
    constraint ck_artifact_status
        check (status in ('active', 'deleting', 'delete_failed', 'deleted')),
    constraint ck_artifact_owner_key
        check (storage_key like 'users/' || user_id::text || '/%')
);

create index ix_artifacts_user_id on public.artifacts(user_id);
create index ix_artifacts_user_created
    on public.artifacts(user_id, created_at);
create index ix_artifacts_user_kind
    on public.artifacts(user_id, kind);

alter table public.artifacts enable row level security;

grant select, insert, update, delete on public.artifacts to authenticated;
grant usage, select on sequence public.artifacts_id_seq to authenticated;

create policy artifacts_owner_all on public.artifacts
for all to authenticated
using (user_id = public.current_app_user_id())
with check (
    user_id = public.current_app_user_id()
    and storage_bucket = 'arya-artifacts'
    and (storage.foldername(storage_key))[1] = 'users'
    and (storage.foldername(storage_key))[2] = public.current_app_user_id()::text
);
