-- Arya_Tool baseline schema for Supabase Postgres.
-- This migration contains no user data, credentials, cookies, or API keys.

create table public.users (
    id bigint generated by default as identity primary key,
    auth_user_id uuid unique null references auth.users(id) on delete restrict,
    tg_id bigint unique null,
    profile_json jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create table public.conversations (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id),
    created_at timestamptz not null default now()
);

create table public.messages (
    id bigint generated by default as identity primary key,
    conversation_id bigint not null references public.conversations(id),
    role varchar(16) not null,
    content text not null,
    created_at timestamptz not null default now()
);

create table public.tasks (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id),
    conversation_id bigint null references public.conversations(id),
    request text not null,
    status varchar(24) not null default 'pending',
    strategy varchar(24) not null default 'react',
    route varchar(24) null,
    model varchar(64) null,
    state_json jsonb not null default '{}'::jsonb,
    result text null,
    error text null,
    created_at timestamptz not null default now(),
    finished_at timestamptz null
);

create table public.steps (
    id bigint generated by default as identity primary key,
    task_id bigint not null references public.tasks(id),
    idx integer not null,
    tool varchar(64) not null,
    params_json jsonb not null default '{}'::jsonb,
    observation_json jsonb not null default '{}'::jsonb,
    status varchar(24) not null default 'pending',
    latency_ms integer not null default 0,
    retries integer not null default 0,
    created_at timestamptz not null default now()
);

create table public.llm_calls (
    id bigint generated by default as identity primary key,
    task_id bigint null references public.tasks(id),
    step_id bigint null references public.steps(id),
    purpose varchar(32) not null,
    provider varchar(32) not null,
    model varchar(64) not null default '',
    prompt_tokens integer not null default 0,
    completion_tokens integer not null default 0,
    cost_usd numeric(18, 8) not null default 0,
    latency_ms integer not null default 0,
    created_at timestamptz not null default now()
);

create table public.scheduled_jobs (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id),
    cron varchar(64) not null,
    task_template text not null,
    enabled boolean not null default true,
    created_at timestamptz not null default now()
);

create table public.notes (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id),
    title varchar(200) not null,
    content text not null default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.todos (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id),
    text text not null,
    done boolean not null default false,
    created_at timestamptz not null default now()
);

create table public.social_accounts (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id),
    platform varchar(32) not null,
    display_name varchar(200) not null,
    external_id varchar(255) not null,
    auth_type varchar(32) not null,
    auth_ref varchar(500) not null,
    status varchar(24) not null default 'active',
    timezone varchar(64) not null default 'Asia/Ho_Chi_Minh',
    daily_post_limit integer not null default 2,
    cooldown_seconds integer not null default 1800,
    last_checked_at timestamptz null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uq_social_account_external_id unique (platform, external_id),
    constraint ck_social_account_daily_limit check (daily_post_limit > 0),
    constraint ck_social_account_cooldown check (cooldown_seconds >= 0)
);

create table public.media_assets (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id),
    type varchar(16) not null,
    local_path text not null,
    storage_backend varchar(16) not null default 'local',
    storage_bucket varchar(100) null,
    storage_key text null,
    original_name varchar(500) not null,
    mime_type varchar(255) not null,
    size_bytes bigint not null,
    sha256 varchar(64) not null,
    duration_seconds double precision null,
    metadata_json jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    constraint uq_media_asset_user_sha256 unique (user_id, sha256),
    constraint ck_media_asset_size check (size_bytes >= 0),
    constraint ck_media_asset_duration
        check (duration_seconds is null or duration_seconds >= 0),
    constraint ck_media_asset_storage
        check (
            (storage_backend = 'local' and storage_bucket is null and storage_key is null)
            or
            (
                storage_backend = 'supabase'
                and storage_bucket is not null
                and storage_key is not null
            )
        )
);

create table public.affiliate_products (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id),
    network varchar(64) not null,
    merchant varchar(200) not null,
    product_name varchar(500) not null,
    product_url text not null,
    affiliate_url text not null,
    sub_id_template varchar(500) not null default '{sub_id}',
    valid_until timestamptz null,
    status varchar(24) not null default 'active',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.social_posts (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id),
    title varchar(300) not null,
    caption text not null,
    hashtags_json jsonb not null default '[]'::jsonb,
    media_asset_id bigint not null references public.media_assets(id),
    affiliate_product_id bigint null references public.affiliate_products(id),
    status varchar(24) not null default 'draft',
    content_hash varchar(64) not null,
    approved_at timestamptz null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.content_generations (
    id bigint generated by default as identity primary key,
    social_post_id bigint not null references public.social_posts(id),
    style_id varchar(64) not null,
    provider varchar(32) not null,
    model varchar(200) not null,
    prompt_fingerprint varchar(64) not null,
    quality_json jsonb not null default '{}'::jsonb,
    retries integer not null default 0,
    prompt_tokens integer not null default 0,
    completion_tokens integer not null default 0,
    latency_ms integer not null default 0,
    cost_usd numeric(18, 8) not null default 0,
    created_at timestamptz not null default now(),
    constraint uq_content_generation_post unique (social_post_id),
    constraint ck_content_generation_retries check (retries >= 0),
    constraint ck_content_generation_prompt_tokens check (prompt_tokens >= 0),
    constraint ck_content_generation_completion_tokens check (completion_tokens >= 0),
    constraint ck_content_generation_latency check (latency_ms >= 0),
    constraint ck_content_generation_cost check (cost_usd >= 0)
);

create table public.publish_jobs (
    id bigint generated by default as identity primary key,
    social_post_id bigint not null references public.social_posts(id),
    social_account_id bigint not null references public.social_accounts(id),
    scheduled_at timestamptz not null,
    status varchar(24) not null default 'queued',
    idempotency_key varchar(64) not null,
    attempt_count integer not null default 0,
    next_retry_at timestamptz null,
    remote_post_id varchar(500) null,
    last_error text null,
    published_at timestamptz null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uq_publish_job_idempotency_key unique (idempotency_key),
    constraint ck_publish_job_attempt_count check (attempt_count >= 0)
);

create table public.publish_attempts (
    id bigint generated by default as identity primary key,
    publish_job_id bigint not null references public.publish_jobs(id),
    attempt_no integer not null,
    status varchar(24) not null,
    request_json jsonb not null default '{}'::jsonb,
    response_json jsonb not null default '{}'::jsonb,
    error_type varchar(64) null,
    error_message text null,
    latency_ms integer not null default 0,
    started_at timestamptz not null default now(),
    finished_at timestamptz null,
    created_at timestamptz not null default now(),
    constraint uq_publish_attempt_number unique (publish_job_id, attempt_no),
    constraint ck_publish_attempt_number check (attempt_no > 0),
    constraint ck_publish_attempt_latency check (latency_ms >= 0)
);

create table public.affiliate_events (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id),
    social_post_id bigint null references public.social_posts(id),
    affiliate_product_id bigint null references public.affiliate_products(id),
    social_account_id bigint null references public.social_accounts(id),
    publish_job_id bigint null references public.publish_jobs(id),
    event_type varchar(24) not null,
    amount numeric(18, 6) not null default 0,
    currency varchar(8) not null default 'VND',
    source varchar(64) not null default 'manual',
    external_event_id varchar(255) null,
    metadata_json jsonb not null default '{}'::jsonb,
    occurred_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    constraint ck_affiliate_event_type
        check (event_type in ('view', 'click', 'commission')),
    constraint ck_affiliate_event_amount check (amount >= 0),
    constraint uq_affiliate_event_source_external
        unique (source, external_event_id)
);

create index ix_conversations_user_id on public.conversations(user_id);
create index ix_messages_conversation_id on public.messages(conversation_id);
create index ix_tasks_user_id on public.tasks(user_id);
create index ix_tasks_conversation_id on public.tasks(conversation_id);
create index ix_steps_task_id on public.steps(task_id);
create index ix_llm_calls_task_id on public.llm_calls(task_id);
create index ix_llm_calls_step_id on public.llm_calls(step_id);
create index ix_scheduled_jobs_user_id on public.scheduled_jobs(user_id);
create index ix_notes_user_id on public.notes(user_id);
create index ix_todos_user_id on public.todos(user_id);
create index ix_social_accounts_user_id on public.social_accounts(user_id);
create index ix_social_accounts_user_status
    on public.social_accounts(user_id, status);
create index ix_media_assets_user_id on public.media_assets(user_id);
create index ix_affiliate_products_user_id on public.affiliate_products(user_id);
create index ix_affiliate_products_user_status
    on public.affiliate_products(user_id, status);
create index ix_social_posts_user_id on public.social_posts(user_id);
create index ix_social_posts_media_asset_id on public.social_posts(media_asset_id);
create index ix_social_posts_affiliate_product_id
    on public.social_posts(affiliate_product_id);
create index ix_social_posts_user_status on public.social_posts(user_id, status);
create index ix_social_posts_content_hash on public.social_posts(content_hash);
create index ix_content_generations_social_post_id
    on public.content_generations(social_post_id);
create index ix_publish_jobs_social_post_id on public.publish_jobs(social_post_id);
create index ix_publish_jobs_social_account_id
    on public.publish_jobs(social_account_id);
create index ix_publish_jobs_due
    on public.publish_jobs(status, scheduled_at, next_retry_at);
create index ix_publish_jobs_account_status
    on public.publish_jobs(social_account_id, status);
create index ix_publish_attempts_publish_job_id
    on public.publish_attempts(publish_job_id);
create index ix_affiliate_events_user_id on public.affiliate_events(user_id);
create index ix_affiliate_events_social_post_id
    on public.affiliate_events(social_post_id);
create index ix_affiliate_events_product_id
    on public.affiliate_events(affiliate_product_id);
create index ix_affiliate_events_account_id
    on public.affiliate_events(social_account_id);
create index ix_affiliate_events_job_id on public.affiliate_events(publish_job_id);
create index ix_affiliate_events_user_occurred
    on public.affiliate_events(user_id, occurred_at);
create index ix_affiliate_events_type_occurred
    on public.affiliate_events(event_type, occurred_at);
create index ix_affiliate_events_post_type
    on public.affiliate_events(social_post_id, event_type);
