-- Owner-scoped metadata and deletion audit state for private artifacts.

create table public.artifacts (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id),
    kind varchar(32) not null,
    original_name varchar(255) not null,
    content_type varchar(255) not null,
    size_bytes bigint not null,
    sha256 varchar(64) not null,
    storage_bucket varchar(100) not null default 'arya-artifacts',
    storage_key text not null,
    status varchar(16) not null default 'active',
    last_error varchar(64) null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    deleted_at timestamptz null,
    constraint uq_artifact_storage_object
        unique (storage_bucket, storage_key),
    constraint ck_artifact_size check (size_bytes >= 0),
    constraint ck_artifact_sha256
        check (sha256 ~ '^[0-9a-f]{64}$'),
    constraint ck_artifact_status
        check (status in ('active', 'deleting', 'delete_failed', 'deleted')),
    constraint ck_artifact_safe_name
        check (
            char_length(original_name) between 1 and 120
            and original_name ~ '^[a-z0-9][a-z0-9._-]*$'
            and right(original_name, 1) ~ '^[a-z0-9]$'
        ),
    constraint ck_artifact_owner_key
        check (
            storage_bucket = 'arya-artifacts'
            and storage_key !~ '(^|/)[.]{1,2}(/|$)'
            and storage_key = (
                'users/' || user_id::text || '/' || left(sha256, 2)
                || '/' || sha256 || '-' || original_name
            )
        )
);

create index ix_artifacts_user_id on public.artifacts(user_id);
create index ix_artifacts_user_created
    on public.artifacts(user_id, created_at);
create index ix_artifacts_user_kind
    on public.artifacts(user_id, kind);

alter table public.artifacts enable row level security;

revoke all on public.artifacts from anon;
revoke all on sequence public.artifacts_id_seq from anon;
grant select, insert, update, delete on public.artifacts to authenticated;
grant usage, select on sequence public.artifacts_id_seq to authenticated;

create policy artifacts_owner_all on public.artifacts
for all to authenticated
using (
    user_id = public.current_app_user_id()
    and storage_bucket = 'arya-artifacts'
    and sha256 ~ '^[0-9a-f]{64}$'
    and char_length(original_name) between 1 and 120
    and original_name ~ '^[a-z0-9][a-z0-9._-]*$'
    and right(original_name, 1) ~ '^[a-z0-9]$'
    and storage_key !~ '(^|/)[.]{1,2}(/|$)'
    and storage_key = (
        'users/' || public.current_app_user_id()::text || '/'
        || left(sha256, 2) || '/' || sha256 || '-' || original_name
    )
)
with check (
    user_id = public.current_app_user_id()
    and storage_bucket = 'arya-artifacts'
    and sha256 ~ '^[0-9a-f]{64}$'
    and char_length(original_name) between 1 and 120
    and original_name ~ '^[a-z0-9][a-z0-9._-]*$'
    and right(original_name, 1) ~ '^[a-z0-9]$'
    and storage_key !~ '(^|/)[.]{1,2}(/|$)'
    and storage_key = (
        'users/' || public.current_app_user_id()::text || '/'
        || left(sha256, 2) || '/' || sha256 || '-' || original_name
    )
);
